### ISSUE TITLE
Can't move blocks in data flow graph mode

### ISSUE THREAD

**Issue by Achllle** [team-vigir/flexbe_behavior_engine#100]
When in the state machine editor, blocks' location freezes after one move after enabling the data flow graph mode.

## steps to reproduce

1. launch the flexbe app
2. open any behavior, e.g. example behavior
3. in the state machine editor, select 'data flow graph'
4. move a state and drop it. Try moving it around again, this will fail.

Once blocks lock into place, you can only move any block again by relaunching FlexBE.

**Comment by pschillinger** [comment]
Need to check, but I would assume this has been introduced recently by [this commit](https://github.com/FlexBE/flexbe_app/commit/a4093a566a8e1f45c5fa3d43aef4d8e7f74f1ebc).
