### ISSUE TITLE
on_enter is called after pause and stop execution

### ISSUE THREAD

**Issue by Achllle** [team-vigir/flexbe_behavior_engine#103]
## Description

When you pause a state, say an action client, and then click on 'Stop Execution', the `on_enter` method gets called.

I would say this is unwanted behavior, since you can't cancel the now continuing execution anymore.

**Comment by pschillinger** [comment]
When I tried to replicate, I observed the following event sequence:
- on_pause
- (clicked "Stop Execution")
- on_resume
- on_exit
- on_stop

Still, on_resume and on_exit should both not be required here.

**Comment by pschillinger** [comment]
Released with 1.2.4
