### ISSUE TITLE
headless in install space

### ISSUE THREAD

**Issue by HannesBachter** [team-vigir/flexbe_behavior_engine#104]
I'm trying to start my flexbe statemachine with the [`execute_behavior` action](http://wiki.ros.org/flexbe/Tutorials/Running%20Behaviors%20Without%20Operator#Behavior_Action) on a workspace build in install space. The action server cannot find the behavior`.py` because it seems to be looking [in the `src` space](https://github.com/team-vigir/flexbe_behavior_engine/blob/19c29cc61995497ac8bbeefd28992cca98eae769/flexbe_widget/src/flexbe_widget/behavior_action_server.py#L85).  Has the `execute_behavior` action been used with behaviors from the install space before? 

Edit: same for the [flexbe_onboard](https://github.com/team-vigir/flexbe_behavior_engine/blob/19c29cc61995497ac8bbeefd28992cca98eae769/flexbe_onboard/src/flexbe_onboard/flexbe_onboard.py#L175) and [behavior_launcher](https://github.com/team-vigir/flexbe_behavior_engine/blob/b11fef09d6fbbd09f2624106656493720cfb50f1/flexbe_widget/src/flexbe_widget/behavior_launcher.py#L77). Seems like flexbe cannot be working in install space at all?

Another general question: are behaviors supposed to be python modules or executables?

**Comment by pschillinger** [comment]
Thanks for reporting and also directly providing a fix. I will take a
closer look during the next days and adapt the PR if required.

Regarding your question: Behaviors are modules, each provides a class that
implements the behavior. They are not executable, execution is handled by
the onboard engine.
