### ISSUE TITLE
PEP8 and git diffs in autogenerated code

### ISSUE THREAD

**Issue by Achllle** [team-vigir/flexbe_behavior_engine#111]
My linter complains a lot for the default created behaviors and example states. There are mixed tabs and spaces (spaces should be used), `'''` is used for dosctrings instead of `"""`, linebreaks where there shouldn't be any and missing linebreaks in other places, and other [PEP8](https://www.python.org/dev/peps/pep-0008/) violations. The reason this is important is that it confuses `git diff` which shows changes which aren't really there. In some behaviors, saving without making any change causes some lines to be reordered and lines to be added and deleted elsewhere.

**Comment by pschillinger** [comment]
I think making the generated code more deterministic is, in principle, a good idea. Will take a look at that. However, I'm not sure whether I can fully remove all of such "false positives" in a diff.
