### ISSUE TITLE
Catching ProxyActionClient dictionary key errors

### ISSUE THREAD

**Issue by mrunaljsarvaiya** [team-vigir/flexbe_behavior_engine#114]
If a certain action registered with `ProxyActionClient` does not send a goal, the `ProxyActionClient`'s `_result` and `_feedback` dictionaries do not have the relevant keys registered. In this case, calling  `has_feedback()` and `has_result()` throw a `KeyError`.
Is this the expected behavior? It would be desirable to return `None` if the keys have not been registered and maybe throw a warning message.

**Comment by pschillinger** [comment]
Released with 1.2.4
