### ISSUE TITLE
Passing userdata to the sub behavior does not work properly on the develop branch

### ISSUE THREAD

**Issue by fgrcar** [team-vigir/flexbe_behavior_engine#129]
Hi,

I tried the develop branch of this repository because of [this](https://github.com/FlexBE/flexbe_app/issues/66) and I found a bug regarding passing the userdata to the sub behavior.

So, I created a following behavior:
![image](https://user-images.githubusercontent.com/26038239/88553421-8dd2ef00-d025-11ea-9986-42f1be5ef355.png)
![image](https://user-images.githubusercontent.com/26038239/88553510-a6dba000-d025-11ea-944e-7ac2ddb9f161.png)
This behavior just takes an input userdata key and prints it out.

Then I created another behavior which uses the first one.
![image](https://user-images.githubusercontent.com/26038239/88554456-d4751900-d026-11ea-8f45-52a486b3db4d.png)
![image](https://user-images.githubusercontent.com/26038239/88554536-ec4c9d00-d026-11ea-9a9c-fa26568a8857.png)
This behavior just prints out the key which is then passed into the sub behavior.

If I use the develop branch of this repository, the printed logs of the main behavior are:
![image](https://user-images.githubusercontent.com/26038239/88554821-40f01800-d027-11ea-85c6-e814cb9c4b35.png)
That means that the key was not passed properly, because the default was used.
If I run the same behavior on the master, I get the desired logs:
![image](https://user-images.githubusercontent.com/26038239/88555315-ec00d180-d027-11ea-9c38-02c17071909b.png)

I am not sure if I am missing something but it looks like that the passing of the userdata does not work properly on the develop branch.

Best regards, F

**Comment by cjue** [comment]
There are multiple commits related to userdata on develop:
* https://github.com/team-vigir/flexbe_behavior_engine/commit/9c47ebfd18f4290340d39d6ab3b7be8c52389027
* https://github.com/team-vigir/flexbe_behavior_engine/commit/cba554eb413d6dab71ca1819a2e67f45f1c283af
* https://github.com/team-vigir/flexbe_behavior_engine/commit/9acc3c859822290b29249abda32a2a7a59b1bbb4

I also noticed another bug on develop, where userdata is not passed along between states when the behavior does not define *any* default userdata values (in the State Machine Userdata dashboard section).

**Comment by pschillinger** [comment]
Sorry for my delay in addressing this, but both issues should be fixed now by the above commit. Please let me know if you still observe any unexpected behavior.
