### ISSUE TITLE
create_repo [your_project_name] created in /devel/lib

### ISSUE THREAD

**Issue by rojas70** [team-vigir/flexbe_behavior_engine#13]
http://philserver.bplaced.net/fbe/download.php
In this download documentaiton, one is told to create one own's repository by using the following command:

````rosrun flexbe_widget create_repo [your_project_name]````

It is said that this creates a new local git repository for your custom states and behaviors. And that we can build and source. 

However, I found that this repository is actually created in devel/lib and portion of my workspace. As such, this package is not built with catkin_make... 

Are we to manually move the package to somewhere inside the src folder of the workspace?

In doing so, I could get `roslaunch flexbe_onboard behavior_testing.launch` to run properly.

**Comment by pschillinger** [comment]
Yes, the repo should be located under src. The script will create the new repo wherever it is executed. I will mention this more clearly in the instructions and try to add a src folder warning.

**Comment by rojas70** [comment]
Thanks.
