### ISSUE TITLE
Can't execute behavior twice if it contains a ProxyServiceCall (Introduced with dd5fc2d)

### ISSUE THREAD

**Issue by kkonen** [team-vigir/flexbe_behavior_engine#130]
With commit dd5fc2d6c01459bd1e06e05eb861fd209e839a96 the following bug was introduced:

ProxyServiceCaller.call(Topic, Request) crashes with the following error
```
super() argument 1 must be type, not None
```
When executing a behavior a second time.

**Comment by fgrcar** [comment]
An similar issue has already been resolved [here](https://github.com/FlexBE/flexbe_app/issues/66).
I hope it helps you.

**Comment by kkonen** [comment]
I will check it out. Thank you!

**Comment by kkonen** [comment]
Indeed fixes the problem. Closing this issue.
