### ISSUE TITLE
Unkown behavior execution breaks flexbe server

### ISSUE THREAD

**Issue by StefanFabian** [team-vigir/flexbe_behavior_engine#133]
If you send a goal with an empty `behavior_name` field or a  behavior name that doesn't exist, the flexbe server outputs the following:
```
[INFO] [1604929126.763544, 9.797000]: Received a new request to start behavior: 
[WARN] [1604929126.767106, 9.799000]: Did not find behavior '' in libary, updating...
[ERROR] [1604929128.725823, 10.978000]: SimpleActionServer.internal_goal_callback - exception
```
After that, any subsequent execute behavior action goal seems to be ignored rendering the flexbe server essentially dead.
I know it shouldn't be called with wrong values in the first place but if that happens, the server should probably handle it more graceful.

**Comment by pschillinger** [comment]
Good catch, thanks for reporting! Should be fixed now on develop.
