### ISSUE TITLE
runtime error: "buffer is too small for requested array" and "Failed to execute state"

### ISSUE THREAD

**Issue by stlslm** [team-vigir/flexbe_behavior_engine#140]
hi, 

I am having a behavior that runs correctly in one machine, but on another machine, it receives a runtime error when executing a state with:

`[ERROR][time] failed to execute state myState`
`buffer is too small for requested array`
`[ERROR][time] failed to execute state myState`

since I just start to use Flexbe, I haven't got a better insight as to what might cause this error when executing a state.

I failed to trace this error "buffer is too small..." since the error message does not exist anywhere. As far as I can tell, it should be related to this [line](https://github.com/team-vigir/flexbe_behavior_engine/blob/96801db5ef93940632564e496c04791c6ca207e4/flexbe_core/src/flexbe_core/core/operatable_state_machine.py#L100) or this [line](https://github.com/team-vigir/flexbe_behavior_engine/blob/96801db5ef93940632564e496c04791c6ca207e4/flexbe_core/src/flexbe_core/core/concurrency_container.py#L95) 

but I got no further clue under the hood of the exception catch.

Any hint would be appreciated  

Thank you.

**Comment by dcconner** [comment]
Did you ever track this down more to find the source of the error?  It looks like it would be deep in the code.

If still an issue, I'd add a traceback handling to the course to get more information.

**Comment by dcconner** [comment]
Closed without further information
