### ISSUE TITLE
Ros2?

### ISSUE THREAD

**Issue by samuk** [team-vigir/flexbe_behavior_engine#156]
Are there any plans to port/re-impliment on Ros2?

**Comment by LoyVanBeek** [comment]
See https://github.com/team-vigir/flexbe_behavior_engine/issues/65

**Comment by dcconner** [comment]
Duplicating latest comment in #65, and closing this issue as duplciate:

We are working on a port and are coordinating with @pschillinger

We have issued an early alpha port that we are in the process of testing. Please take a look and test if you are able.
We hope to complete testing and issue a pull request for an official release in early 2022.

https://github.com/CNURobotics/flexbe_app/tree/ros2-devel-alpha
https://github.com/CNURobotics/flexbe_behavior_engine/tree/ros2-devel-alpha

**Comment by samuk** [comment]
Thanks..
