### ISSUE TITLE
Concurrent state does not operate as expected

### ISSUE THREAD

**Issue by bkvaluemeal** [team-vigir/flexbe_behavior_engine#18]
During testing I have noticed that the concurrent state only calls the `on_start()` and `on_stop()` functions of the state that receives the arrow. In addition, when running a looping behavior like the one described in the image, only the `on_enter()` and `on_exit()` functions are called of the state that receives the initial state arrow inside the concurrent state. 

I would expect all of the `on_enter()` and `on_exit()` functions for each internal state to get called every time the concurrent state is activated.

It works perfect the first time the concurrent state is activated, but then doesn't any other time the state is activated after the first. Killing the behavior and restarting it fixes the problem. I don't have to restart FlexBE for that to happen.

![concurrent_test](https://cloud.githubusercontent.com/assets/3835053/17635393/127090cc-60a5-11e6-9665-148de12c1e33.png)

Concurrent test behavior:
[concurrent_test_behaviors.tar.gz](https://github.com/team-vigir/flexbe_behavior_engine/files/416053/concurrent_test_behaviors.tar.gz)

Log output when running the behavior:
[concurrent_test.txt](https://github.com/team-vigir/flexbe_behavior_engine/files/416054/concurrent_test.txt)

The logger I used to test:
[verbose_logger.txt](https://github.com/team-vigir/flexbe_behavior_engine/files/416055/verbose_logger.txt)
(It's a .py in disguise. GitHub wouldn't let me upload a .py)

**Comment by pschillinger** [comment]
Thanks for reporting and the helpful files! Yes, the events didn't get triggered correctly. I fixed it and tested your behavior, looks correct now.
