### ISSUE TITLE
sudo required for create_repo

### ISSUE THREAD

**Issue by dcconner** [team-vigir/flexbe_behavior_engine#4]
The create_repo script tries to install rosbridge, which requires super user privileges.

Can we just make rosbridge-server a run dependency, and not do this sudo.

Or can we just use `dpkg -s ros-jade-rosbridge-server` and check return type, and only try sudo if not installed?

**Comment by skohlbr** [comment]
We use this approach to only run sudo if required:
https://github.com/tu-darmstadt-ros-pkg/centaur_robot_tutorial/blob/master/update.sh#L54
I think this could also be done in this case?

**Comment by dcconner** [comment]
That works for my issue.  I can make the change, but want Philipp to weigh in first.

**Comment by pschillinger** [comment]
Sounds good, feel free to integrate the change Stefan suggested or assign it back to me.
