### ISSUE TITLE
behaviour-2 process has died 

### ISSUE THREAD

**Issue by mjkl-gh** [team-vigir/flexbe_behavior_engine#48]
When trying to start using roslaunch flexbe_onboard behavior_onboard.launch  or actually any other launch file the behaviour engine process keeps on dieing giving the following error code

[behavior-2] process has died [pid 675, exit code 1, cmd /home/maarten/ws_moveit/src/flexbe_behavior_engine/flexbe_onboard/bin/start_behavior __name:=behavior __log:=/home/maarten/.ros/log/bb791a4c-f5fd-11e7-95db-54ee756d3429/behavior-2.log].
log file: /home/maarten/.ros/log/bb791a4c-f5fd-11e7-95db-54ee756d3429/behavior-2*.log

When viewing the log file mentioned it does not reveal any more clues. Ive tried reinstalling and recompiling from source but the error will stay.

Weird thing is initially it did work for a few hours until I also added the generic_flexbe_states  package to my workspace and recompiled.

I'm entirely new to flexbe and might have set up something wrong

**Comment by MaartenKleijwegt** [comment]
Turns out it was a dependency problem. fixed it by:

Shutting down all nodes and terminals
Start new terminal

cd YOUR_WORSPACE/src
rosdep install --from-paths src --ignore-src -r -y
cd ..
catkin build

source new install files
Restart Flexbe
