### ISSUE TITLE
flexbe_testing skips tests which have problems

### ISSUE THREAD

**Issue by AndyIII** [team-vigir/flexbe_behavior_engine#53]
I recently added my first FlexBE state tests, so forgive me if I've done something incorrectly.  The first test I made reported two tests, foo_pass and foo_outcome, both of which passed.  The second test I made found a bug (yay!), but didn't report any test errors or failures (boo!).  It spit out a traceback from the on_enter or on_exit of the state (actually, it was both - one was missing userdata in the test yaml, the other was the actual bug - not checking for availability of a ProxyActionClient before checking has_result).  The test was merely **NOT reported** and not marked as a failure or error.  I would have expected all sub-tests (foo_pass and foo_outcome) to be marked ERROR (not FAILURE) in the test results since the test broke instead of arriving at the wrong result/outcome.  This is not suitable for automated testing as is, unless I'm missing some critical configuration somewhere.

**Comment by pschillinger** [comment]
Thank you for reporting and sorry for the delay! This should be fixed by now by the commit 66ede70e8adaea4703eafa6abf9762c76fc00e44.
