### ISSUE TITLE
Did not find behavior with requested name

### ISSUE THREAD

**Issue by SDBonhof** [team-vigir/flexbe_behavior_engine#54]
I just reinstalled flexbe after having to reinstall Ubuntu. I configured the widget, found my behaviors, but as soon as I try to run it i get the following error message:
[ERROR] [1525697270.562160]: Did not find behavior with requested name: Speed_challenge

I tried to make a new behavior to test whether I can run new behaviors. I can successfully save the test behavior, but i get the same error message when I try to run it.

I have already tried sourcing my setup.bash and catkin_make but to no avail.\

I am using the old chrome app. I cannot figure out how to set the workspace in the new app, so I'm sticking to chrome right now.

Update:
I have found out that I **can** run the example state in the repo I freshly make in my own catkin_ws. So, my guess is that flexbe doesn't recognise my own git folder with behaviors and states as a repository. How can I add this folder as a repo for flexbe?

**Comment by SDBonhof** [comment]
I managed to fix it. For anyone getting this error as well:
If you already have a repo for flexbe: use the rosrun flexbe create_repo [project_name] command with your project name being the name of the existing repo **without** _behaviors at the end. 

Also, make sure that the workspace this repo is in is properly sourced in all terminals.

**Comment by tiralonghipol** [comment]
hey! how and where did you set the path in order to find the created behaviors inside the app? 
Thanks
