### ISSUE TITLE
Can't connect FlexBE from different systems

### ISSUE THREAD

**Issue by utkarsh447** [team-vigir/flexbe_behavior_engine#63]
Hi, I am following FlexBE tutorials. The issue is I can't connect the flexBE from different systems. My goal is to run FlexBE in one system and when behaviour is launched it should work on my Pi and show updates on my system.
I am using ros-bridge in my Pi 
using command 
`rosrun rosbridge_server rosbridge_websocket` 
and i get this output with one error when client is gets connected.
![screenshot from 2018-11-15 12-45-31](https://user-images.githubusercontent.com/8874843/48536469-b3ad7400-e8d4-11e8-8c4a-294be4ea31cd.png)

But the system on which i want the FlexBE to run, I get this,
on executing this command, 
`roslaunch flexbe_onboard behavior_onboard.launch`
![screenshot from 2018-11-15 12-52-38](https://user-images.githubusercontent.com/8874843/48536703-5e259700-e8d5-11e8-99a4-9d80fb65c3ad.png)

Here I got connected from ROS config. But getting on board status "disconnected", Furthermore, I also followed the issue: [https://github.com/team-vigir/flexbe_behavior_engine/issues/28](url) but still i can't get it online.
Also, i can't find any means to run the behaviour. 
Please suggest suitable way if i am missing some steps or making a mistake?

**Comment by pschillinger** [comment]
There might be two problems here, actually:

* The first screenshot appears to be a race condition within rosbridge, I have seen it previously in several cases.
* As it looks like in the second screenshot, you did not yet add any states and behavior packages. Did you follow the instructions here for installing the Chrome app?: http://philserver.bplaced.net/fbe/download.php

In any case, I can recommend to switch to the newer FlexBE App instead of the Chrome app, see #46. This will give you several improvements including that both of the above issues are not relevant for the FlexBE App anymore. Is this an option for you?

**Comment by utkarsh447** [comment]
Hi, Thank you for response, I followed your steps and got the new FlexBE app working, But still I can't reach my solution.
First I setup working Master Slave connection between two systems.
In Master System, I got connected by rosbridge
![5](https://user-images.githubusercontent.com/8874843/48600048-4fe88100-e990-11e8-9c84-2a10b6113ed8.png)

And testing the "Example Behaviour" sample program
In Master, I ran `roslaunch flexbe_app flexbe_ocs.launch` , then loaded the "Example Behaviour" code. 
and on Slave, I ran `roslaunch flexbe_onboard behavior_onboard.launch`

On Master, After running, I get the output as 
![2](https://user-images.githubusercontent.com/8874843/48600224-1106fb00-e991-11e8-91ad-9b5138835c81.png)

I get this message whenever I click on "Start Execution".
Also, at slave I get the same error:
![4](https://user-images.githubusercontent.com/8874843/48600270-398ef500-e991-11e8-9cf9-073018244974.png)

Please tell me the reason for this error, and how can this be solved?

**Comment by utkarsh447** [comment]
> Hi, Thank you for response, I followed your steps and got the new FlexBE app working, But still I can't reach my solution.
> First I setup working Master Slave connection between two systems.
> In Master System, I got connected by rosbridge
> ![5](https://user-images.githubusercontent.com/8874843/48600048-4fe88100-e990-11e8-9c84-2a10b6113ed8.png)
> 
> And testing the "Example Behaviour" sample program
> In Master, I ran `roslaunch flexbe_app flexbe_ocs.launch` , then loaded the "Example Behaviour" code.
> and on Slave, I ran `roslaunch flexbe_onboard behavior_onboard.launch`
> 
> On Master, After running, I get the output as
> ![2](https://user-images.githubusercontent.com/8874843/48600224-1106fb00-e991-11e8-91ad-9b5138835c81.png)
> 
> I get this message whenever I click on "Start Execution".
> Also, at slave I get the same error:
> ![4](https://user-images.githubusercontent.com/8874843/48600270-398ef500-e991-11e8-9cf9-073018244974.png)
> 
> I also got heartbeat:
> ![6](https://user-images.githubusercontent.com/8874843/48601966-a1e0d500-e997-11e8-9ec5-5cb8c74fa5f4.png)
> 
> Please tell me the reason for this error, and how can this be solved?

Hi, I solved this issue, My code wasn't on the slave system. After pasting the code, it worked.

**Comment by utkarsh447** [comment]
> There might be two problems here, actually:
> 
> * The first screenshot appears to be a race condition within rosbridge, I have seen it previously in several cases.
> * As it looks like in the second screenshot, you did not yet add any states and behavior packages. Did you follow the instructions here for installing the Chrome app?: http://philserver.bplaced.net/fbe/download.php
> 
> In any case, I can recommend to switch to the newer FlexBE App instead of the Chrome app, see #46. This will give you several improvements including that both of the above issues are not relevant for the FlexBE App anymore. Is this an option for you?

Hi, @pschillinger , Thank you for responding in short amount of time.
In your reply, You mentioned about the new [FlexBE App](https://github.com/FlexBE/flexbe_app), I successfully ported on that and able to use it. 

In the new App, Is it possible to run the selected behavior from command line instead of manually selecting them from the GUI?

**Comment by pschillinger** [comment]
Great to hear that it works now!

Yes, it is possible to run behaviors without the user interface, either
from command line/launch file or as action calls. See the following
tutorial for details:
http://wiki.ros.org/flexbe/Tutorials/Running%20Behaviors%20Without%20Operator

As mentioned there, you can also attach the user interface to an already
running behavior that you launched without it, e.g., for debugging. When
using the new FlexBE App, the launch file is:
roslaunch flexbe_app flexbe_ocs.launch

**Comment by utkarsh447** [comment]
Thanks @pschillinger , it is working as it should. The only difference is I have to run the flexBE app in super user mode and then running the behavior in my Pi, I was able to see the changes in my main PC.

**Comment by utkarsh447** [comment]
Hi @pschillinger , I am facing another Issue,
I have made a gif of that, please refer to the below gif:
![peek 2018-11-19 14-42](https://user-images.githubusercontent.com/8874843/48697068-b0362780-ec09-11e8-9ca4-e0b4b31f3fa3.gif)

The flexBE app is running in my remote PC using command: `roslaunch flexbe_app flexbe_ocs.launch` and in my pi, the flexBE onboard is running using command: `roslaunch flexbe_onboard behavior_onboard.launch`.

As you can see, there are 4 states in **StateMachine Editor**, First State displays "Hello World", Second state has 5 second wait timer, Third state displays "End of FSM" and the fourth state also has 3 second timer. Also, the autonomy level of all states are set to "High" and **Block Transition which require atleast "Low" autonomy** is set.

But on executing the behavior using `rosrun flexbe_widget be_launcher -b 'behavior_fsm_drone'`, You can see the states are not updating but logs are coming as it should. I am getting logs on Pi Onboard too.

Please suggest me the issue i am facing and how it can be solved?

**Comment by pschillinger** [comment]
I need to check further, but I think what happens is the following.

There are two different ways to run a behavior: (1) in interactive mode using the app and (2) in fully autonomous mode, e.g., by using the `rosrun ...` command.

It looks like those two different ways are mixed in your case. When you start the behavior, it runs in mode (2) and therefore, has the shared autonomy disabled. Still, the app appears to recognize the behavior start and directly monitors the execution.

What should happen is that the app notifies you that a behavior has started and asks if you want to attach. Before attaching, mode (2) is active and upon attaching, it will switch to (1), including the shared autonomy.

**Comment by utkarsh447** [comment]
Hi @pschillinger , I had it solved this morning.
I was using flexBE with ssh added on it. To get the files to be modified on different systems, i had to run it in super user mode. Whereas the onboard on the bot was running on the normal mode (which was the root of this issue). On giving the onboard the super user access, it got solved.
I want to thank you for showing your concern and providing support.
