### ISSUE TITLE
Error in state machine conversion

### ISSUE THREAD

**Issue by janhavi19** [team-vigir/flexbe_behavior_engine#64]
We are trying to convert our existing state machine of move base youbot to flexbe but we dont want to disturb the structure of the code. So when we try to do so by keeping all the states in same file. The problem is we get a error saying loop back outcome not present.Please can you suggest a method for doing this.

**Comment by pschillinger** [comment]
Not sure if I can help you that much without further information, but here is some general info:

Multiple states in a single file is possible, but will not work in combination with the FlexBE App. If you want to use its features, I recommend to split the states in one state class per file as, e.g., in flexbe_states. This should also help you for re-usability in the long run. It does not explain the error though.

All states in FlexBE inherit from EventState, i.e, `from flexbe_core import EventState`. Could this be the reason for your error?

It would be great if you can share more details if you need further help. If you don't want to post details publicly, you can also write me via this [contact form](http://philserver.bplaced.net/fbe/contact.php).
