### ISSUE TITLE
subscriber_state not getting messages even though they are published.

### ISSUE THREAD

**Issue by galbra-rnd** [team-vigir/flexbe_behavior_engine#78]
Hello,
I have a mavros running, that publishing "/mavros/state" topic..
![Screenshot from 2019-08-28 10-41-56](https://user-images.githubusercontent.com/54571943/63835690-a4d61080-c980-11e9-81e9-b01961bd5e07.png)

And i have a state subscriber_state (i've called it 'disarm'), that subscribes (supposedly) to this topic:
![Screenshot from 2019-08-28 10-44-27](https://user-images.githubusercontent.com/54571943/63835762-d18a2800-c980-11e9-9ed0-533cff467628.png)
Where "safety_stopic=/mavros/state".

But, when i run this behavior, this state enters to its executing function, and return with empty hands, because this condition
```
if self._sub.has_msg(self._topic) or not self._blocking:
```
is false, even though that topic is being published for sure:
![Screenshot from 2019-08-28 10-48-16](https://user-images.githubusercontent.com/54571943/63836002-5a08c880-c981-11e9-9448-7964add857c0.png)

What am i missing here?

Thanks Gal.

**Comment by pschillinger** [comment]
Thanks for reporting! However, I have not been able to reproduce the observed behavior. Can you run the following:

    roslaunch flexbe_states run_tests.launch

and check whether the `subscriber_state_pose.test` fails as well?

**Comment by galbra-rnd** [comment]
Hey, sorry for the delay.

It is not relevant anymore.
Gal
