### ISSUE TITLE
Logger stalls States

### ISSUE THREAD

**Issue by semeyerz** [team-vigir/flexbe_behavior_engine#79]
If you have a logger in your state, it can not run faster than 10Hz.
Adding more loggers increases slow down.

This line introduces the stalls:
https://github.com/team-vigir/flexbe_behavior_engine/blob/b11fef09d6fbbd09f2624106656493720cfb50f1/flexbe_core/src/flexbe_core/logger.py#L36

**Comment by pschillinger** [comment]
Interesting catch, thanks for reporting! I will take a closer look to figure out why this has been added.

**Comment by pschillinger** [comment]
I couldn't find a reason why this would still be required and thus, removed it.

**Comment by pschillinger** [comment]
Fix released with version 1.2.2
