### ISSUE TITLE
Unable to run flexbe app due to error flexbe_app/nwjs/nw: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by sharathrjtr** [team-vigir/flexbe_behavior_engine#80]
I'm trying to run the flexbe app on nvidia jetson Tx2 installed with ubuntu 18.04 and ros melodic.
But I've been getting the following error
`
$ rosrun flexbe_app run_app
`
`
/home/jetson/catkin_ws/src/flexbe_app/bin/run_app: line 16: /home/jetson/catkin_ws/src/flexbe_app/nwjs/nw: cannot execute binary file: Exec format error
`
Could you please tell me how can i solve this?

**Comment by pschillinger** [comment]
It looks like the architecture used by Jetson is not supported by nwjs. I
don't have a device to test it, but you can take a look at their website (
https://nwjs.io) whether there exists a binary for your case or
instructions to build from source.

If this works, you can replace the executable at flexbe_app/nwjs/nw by your
specific version and replace the rest of the folder content accordingly.

**Comment by sharathrjtr** [comment]
I was able to run the app after downloading the [https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/tag/v0.23.7](nwjs arm64 binaries) and installing libgconf-2 library with command
`sudo apt -y install libgconf2-4`
Thanks for the help.

Note: the binaries available in [https://github.com/LeonardLaszlo/nw.js-armv7-binaries](url) is for armv7 and it cannot be used on Nvidia Jetson Tx2. Specifically download [https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/tag/v0.23.7](nwjs-sdk-without-nacl-v0.23.7-linux-arm64.tar.gz) for armv8 architecture.

**Comment by Combinacijus** [comment]
In [nwjs_install](https://github.com/FlexBE/flexbe_app/blob/2ef95e2314e296ac838f757f3ed65bf85cabb196/bin/nwjs_install#L39) changed

```
curl -s -o $TEMPFILE https://dl.nwjs.io/$VERSION/nwjs-$VERSION-$OS-$ARCH.tar.gz
```
To
```
if [[ `uname -m` == "aarch64" ]]; then
	# Arm  binary for Jetson
	curl -s -L https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/download/v0.23.7/nwjs-sdk-without-nacl-v0.23.7-linux-arm64.tar.gz > $TEMPFILE
else
	curl -s -o $TEMPFILE https://dl.nwjs.io/$VERSION/nwjs-$VERSION-$OS-$ARCH.tar.gz
fi
```
And normal catkin build works on Jetson although binary version is old so it's more like workaround
