### ISSUE TITLE
ProxyActionClient : Issues with sending custom goal

### ISSUE THREAD

**Issue by RajArdeshna** [team-vigir/flexbe_behavior_engine#81]
Hi,

I have a custom Action Server written in C++ where i just have to send the 'Proportional' value in order to perform the action. In SMACH I implemented this state using the following example and its working fine.
I am passing my proportional value as "goal_slots=['p']" in SMACH state

![goal_from_user_data](https://user-images.githubusercontent.com/24778613/65311602-f98c3600-db90-11e9-80f9-24a68d89b1c7.png)

But, looking at the 'ProxyActionClient' implemented in FlexBe, as per my understanding, only sending the 'Fixed goal message' is possible (Correct me if i am wrong) using the function 
                                                  client.send_goal(topic,goal) 
as described in the following example.

![Fixed_goal_message](https://user-images.githubusercontent.com/24778613/65311728-496afd00-db91-11e9-998b-c02ce42d5468.png)

So, is there a way to send just the 'Proportional' value to my custom written Action server using FlexBe?

**Comment by pschillinger** [comment]
It is also possible to construct an action goal from userdata input keys.
In general, this tutorial might be helpful for you:
[Developing Actionlib States](
http://wiki.ros.org/flexbe/Tutorials/Developing%20Actionlib%20States)

**Comment by RajArdeshna** [comment]
Thanks for the quick response. This tutorial solved my problem :)
