### ISSUE TITLE
The States in the Concurrency Container does not Run Parallally as Intended.

### ISSUE THREAD

**Issue by paulsebastian97** [team-vigir/flexbe_behavior_engine#84]
I have created a flexbe behavior to test the working of concurrency container. The concurrency container contains 3 states which should run parallelly. Each of these 3 states basically publishes a unique string to 3 different topics. The value published by the topic is printed using "rostopic echo" ROS command. But when I run the behavior, the 3 concurrency states do not print  the strings simultaneously instead prints the strings one after another. This is not how the parallel states should run in a concurrency container. Instead, all the 3 strings should be printed at once. I have attached my flexbe behavior graph and code.

The below two images show the behavior flow.
![behavior_flow](https://user-images.githubusercontent.com/44846728/68118899-320c8700-ff27-11e9-86a2-a8d01e784a43.png)

![3_states_inside_concurrency_container](https://user-images.githubusercontent.com/44846728/68117740-28355480-ff24-11e9-89a3-af3665ad97b0.png)

I have attached the behavior and the code for the individual states below.
[flexbe_behavior_and_states.tar.gz](https://github.com/team-vigir/flexbe_behavior_engine/files/3803802/flexbe_behavior_and_states.tar.gz)

Am I doing anything wrong here?

**Comment by pschillinger** [comment]
Not sure what exactly you mean by "printed at once" and "one after the other".

One aspect I would like to point out is the difference between parallel and concurrent. In the concurrency container, all children are active at the same time, but they are not parallelized in the sense of multithreading or multiprocessing. Instead, they are indeed processed in sequence and each state is executed at its own rate, but they are the "active" state at the same time.

Underlying assumption here is that none of the execute methods is actually a blocking or time-consuming operation, as in general for FlexBE.

Does this cover your observation or do you think there is something wrong in the way the concurrency is working in practice? Note that there is the recent issue reported in #87 that might have an effect on your example as well.
